### PR TITLE
Upgrade Kresus to 0.14.0

### PR DESCRIPTION
**Pull request by nicofrand**
Hi,

Kresus shipped a new version, this MR upgrades the current Kresus version :).

### CODE REVIEW

**Comment by Jibec** [comment]
Please change the version number in manifest to be 0.14.0~ynh1 and update the readme.

Would you like to learn packaging and how to take into account the **salt** thing?

**Comment by nicofrand** [comment]
I updated the manifest file, the Readme was already updated (unless there is something) I did not see?
For the salt thing I was thinking about doing it later (maybe a basic sed) if that's OK.

**Comment by Jibec** [comment]
my bad, indeed Readme was already ok.

the salt thing can be handle by YunoHost

see **ynh_string_random** in https://yunohost.org/#/packaging_apps_helpers_en

but this design prevent the user to move from one server to another with his data, because he will never know what is the salt use by his server, and/or change the salt use by the destination server

**Comment by Jibec** [comment]
to make upgrade works from 0.13, you have to add a condition in upgrade script:

```
--- a/scripts/upgrade
+++ b/scripts/upgrade
@@ -171,7 +171,12 @@ chmod -R 750 "$final_path/data/"
 
 # Set permissions to config files
 chown "$app" "$final_path/config.ini"
-chmod 600 "$final_path/config.ini" "$final_path/data/weboob-data/backends"
+chmod 600 "$final_path/config.ini"
+
+if [ -f "$final_path/data/weboob-data/backends" ]
+then
+	chmod 600 "$final_path/data/weboob-data/backends"
+fi

 #=================================================
 # RELOAD NGINX
```

you should also add an automatic test check (this is how I discovered the upgrade bug)
```
--- a/check_process
+++ b/check_process
@@ -15,6 +15,7 @@
 		setup_private=1
 		setup_public=0
 		upgrade=1
+		upgrade=1		from_commit=c455d5def074eb4012e9c1d07e8e2abba38a3aa9
 		backup_restore=1
 		multi_instance=1
 		incorrect_path=1
@@ -35,4 +36,8 @@
 	Level 10=0
 ;;; Options
 Email=jean-baptiste@holcroft.fr
-Notification=all
\ No newline at end of file
+Notification=all
+;;; Upgrade options
+	; commit=c455d5def074eb4012e9c1d07e8e2abba38a3aa9
+		name=Upgrade from 0.13
+manifest_arg=domain=DOMAIN&path=/
```

**Comment by nicofrand** [comment]
Is that OK now?

**Comment by Jibec** [comment]
yes, thank you :)

**Comment by nicofrand** [comment]
Thank you for the advices and review!

**Comment by Jibec** [comment]
you're welcome, I just finished the salt thing, should be live soon

**Pull request merged**
