### PR TITLE
Upgrade

### LINKED ISSUE #100: Change URL prefix when the app's URL is changed
See https://github.com/YunoHost/example_ynh/blob/master/scripts/change_url.

### LINKED ISSUE #115: Check if Rust is needed
See https://framagit.org/kresusapp/kresus/-/merge_requests/1484

### PR DESCRIPTION
**Pull request by yalh76**
## Problem

- *Fix #115*
- *Fix #100*

## Solution

- *Apply last example_ynh*
- *Follow https://framagit.org/kresusapp/kresus/-/blob/0.18.1/support/docker/Dockerfile-nightly install steps*
- *Install Rust*
- *Implement change_url*

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by nicofrand** [comment]
The autocollits really don't help the review...
The config.ini file should not be edited like that, I'll check for the typos upstream but there are also some parameters that might be case sensitive

**Comment by yalh76** [comment]
> The autocommits really don't help the review... 
what is the autocommits ? the commits from Auto-update README ?



> The config.ini file should not be edited like that, I'll check for the typos upstream but there are also some parameters that might be case sensitive

The config.ini is from https://framagit.org/kresusapp/kresus/-/blob/0.18.1/support/docker/config.example.ini and no parameters has been changed, it's only comments update from the 0.18.1 config.example.ini

**Comment by nicofrand** [comment]
Yep, the one from the Auto-update. Also, mixing several issues make it harder to re-read.

Regarding Rust I am not really sure this is needed, Benjamin only spotted it once I think, but OK.
Regarding the change_url, the main issue was to update the url_prefix, but this should be OK since you seem to be re-creating the config file (could we not just update it, for mu curiosity)?

**Comment by yalh76** [comment]
> Yep, the one from the Auto-update. Also, mixing several issues make it harder to re-read.

Sorry, I should split the commits ..



> Regarding Rust I am not really sure this is needed, Benjamin only spotted it once I think, but OK.
As far as I've seen, rust doesn't seem used during python build

>  Regarding the change_url, the main issue was to update the url_prefix, but this should be OK since you seem to be re-creating the config file (could we not just update it, for mu curiosity)?

Yes we could just update it

**Comment by nicofrand** [comment]
OK, fine by me then. Should we worry about the tests failure though?

**Comment by yalh76** [comment]
> OK, fine by me then. Should we worry about the tests failure though?

Yes we should worry, I will look at it

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
!testme

**Pull request merged**
