### PR TITLE
Fix postgresql missing on upgrade when  creating DB

### LINKED ISSUE #57: Upgrade to Kresus 0.16
Hello,
After a toot on mastodon, I hurried to update kresus.
2 errors:
- the postgres user is missing. I manually create it and relaunch the upgrade
- I don't understand the second error, here are the logs : 
https://paste.yunohost.org/foqutadova.bash

Kresus is still working and my data are ok.

i'm using a virtual machine to use yunohost.

Thanks for your work

### PR DESCRIPTION
**Pull request by nicofrand**
Fixes #57

### CODE REVIEW

**Comment by Jibec** [comment]
thank you nicofrand, it is now time for me to retire, you handle the package really well
please put your name as maintainer and update this page apps.json once this PR is merged: https://github.com/YunoHost/apps/pull/920

**Comment by nicofrand** [comment]
Oh OK. I hope you're not in a burnout situation or something!

I'll edit this app's manifest too one I find out how to have both an author and a maintainer.

**Comment by Jibec** [comment]
Thank you

I'm tired yes, but it's more me not being able to spend a lot of time to
packaging and feeling guilty.
Free libre & open source software is a political choice, but it also is
about doing something we like.
There isn't much fun of knowing you can't do what is required.

**Comment by nicofrand** [comment]
Indeed. I hope you'll find the time to have real fun soon, take care!

**Comment by bnjbvr** [comment]
Take care of yourself @Jibec, and thanks a bunch for all the work that you have done! :hugs:

**Pull request merged**
