### PR TITLE
Harden systemd-service

### PR DESCRIPTION
**Pull request by ArchangeGabriel**
## Problem

Current file is not up-to-date with latest hardening practices.

## Solution

Sync with current best practices.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by ericgaspar** [comment]
!testme

**Comment by nicofrand** [comment]
Hi, 

Thanks for that!

Regarding the dependency commit I'd like to check first why this is needed, testing was expected to be iso with master...

**Comment by ArchangeGabriel** [comment]
Ah sorry, I did not see that I brought another commit. Seems I based my changes on master but open the PR against testing.

When on the testing branch, GitHub says “This branch is 1 commit ahead, 1 commit behind master.”. Indeed the commit hashes are different, https://github.com/YunoHost-Apps/kresus_ynh/commit/308ced32ad05b1f4704e92c8c0613b2e0e879462 vs https://github.com/YunoHost-Apps/kresus_ynh/commit/3e429ee964564f87d35f89280313ab98d794d192.

**Comment by nicofrand** [comment]
OK, now testing and master are really ISO.

The CI seems to indicate there are issues with the installation though. Either due to a temporary connection issue, either to the new directives:

```
61715 INFO DEBUG - ++ wget --tries 3 --no-dns-cache --timeout 900 --no-verbose --output-document=/var/cache/yunohost/download/kresus/app.tar.bz2 https://framagit.org/kresusapp/kresus/-/archive/0.17.4/kresus-0.17.4.tar.bz2
61716 INFO DEBUG - + out='failed: Connection refused.
61717 INFO DEBUG - failed: Connection refused.'
61718 INFO DEBUG - + ynh_die '--message=failed: Connection refused.
```

We'll try again:

!testme

**Comment by nicofrand** [comment]
OK, that's better. Only the private part is failing but that's a CI issue:

> We have a long standing bug in the devCI with that test (it's testing the installation of the app without visitor access, so it expects to be landing on the login page). You can ignore it for the time being.

**Comment by nicofrand** [comment]
Sorry for the time it takes but I would have to spawn a (heavy) new yunohost dev environment to test it!

**Comment by nicofrand** [comment]
Closing in favor of #124 (same but with the yunohost package number updated).

**Comment by nicofrand** [comment]
Thanks a lot @ArchangeGabriel, I made a copy of your PR now that I had time to test it, only to update the version number.
I'll wait for #123 to be merged and then rebase and merge yours!

**Pull request closed without merging**
