### PR TITLE
Harden systemd service

### PR DESCRIPTION
**Pull request by nicofrand**
This is a sync with current ArchLinux file.

## Problem

- Current file is not up-to-date with latest hardening practices.

## Solution

- Sync with current best practices.

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by nicofrand** [comment]
Supersedes #116 (I only updated the manifest with the version number, everything is from @ArchangeGabriel).

**Comment by ArchangeGabriel** [comment]
I’ve added a comment regarding the missing bit: https://github.com/YunoHost-Apps/kresus_ynh/pull/123#issuecomment-1159794283. I did not need it in Arch because the default is to write the log under the datadir.

**Comment by nicofrand** [comment]
> I’ve added a comment regarding the missing bit: [#123 (comment)](https://github.com/YunoHost-Apps/kresus_ynh/pull/123#issuecomment-1159794283). I did not need it in Arch because the default is to write the log under the datadir.

Thanks! Just to be sure, if the logs are in `/var/log/__APP__` (we replace `__APP__` with "kresus") we set `LogsDirectory=/var/log/__APP__` right?
And we should restore `ProtectSystem=strict` instead of `ProtectSystem=full`?

**Comment by nicofrand** [comment]
Also, I wonder if this is still needed: https://github.com/YunoHost-Apps/kresus_ynh/blob/master/scripts/install#L176-L178

**Comment by yalh76** [comment]
> Tested in a VM without issue, and `/var/log/kresus/kresus.log` works fine too (I made sure to remove it before installing this branch to ensure it is created as expected).
> 
> @yalh76 Would you care to test it too please?

I don't user Kresus and I don't what do this app and how it works :/.
If you tests are ok, I trust you

**Pull request merged**
