### PR TITLE
Upgrade

### PR DESCRIPTION
**Pull request by yalh76**
## Solution

- *Apply last example_ynh*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by nicofrand** [comment]
Hi!

Can we keep the current systemd conf? There already is a PR for that, pre-dating this one and tested manually (also it's from the maintainer of the Arch Linux package)?

**Comment by yalh76** [comment]
Service failed to start because it couldn't access the log file at `/var/log/kresus/kresus.log`

**Comment by nicofrand** [comment]
I tested manually #116/#124 and the service started without issues…

**Comment by nicofrand** [comment]
OK, I don't know why it worked on my VM but #125 seems to confirm the log issue…

**Comment by ArchangeGabriel** [comment]
For the log issue, instead of relaxing system protection, you should set `LogsDirectory=kresus`.

**Pull request merged**
